# Generated by Django 4.0.4 on 2023-06-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=75, null=True)),
                ('prenom', models.CharField(max_length=75, null=True)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('nom_utilisateur', models.CharField(max_length=50, null=True)),
                ('mdp', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IBAN', models.CharField(max_length=50, null=True)),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bankapp.client')),
            ],
            options={
                'db_table': 'compte',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=75, null=True)),
                ('prenom', models.CharField(blank=True, max_length=75, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('date_arrive', models.DateTimeField(blank=True, null=True)),
                ('nom_utilisateur', models.CharField(blank=True, max_length=50, null=True)),
                ('mdp', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'personnel',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('compte_cible', models.ForeignKey(blank=True, db_column='compte_cible', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_cible', to='bankapp.compte')),
                ('compte_source', models.ForeignKey(blank=True, db_column='compte_source', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_source', to='bankapp.compte')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
